---
- become: false
  connection: local
  hosts: localhost
  gather_facts: false
  name: "Setup new macbook"

  pre_tasks:
    - community.general.homebrew:
        update_homebrew: true
        upgrade_all: true

    - community.general.homebrew:
        name: git
        state: latest
        update_homebrew: true

  tasks:
  - name: install tomcat
    community.general.homebrew:
      name: tomcat@9, nginx, openssl, homebrew/cask/jetbrains-toolbox, homebrew/cask/azure-data-studio, homebrew/cask/postman, homebrew/cask/docker
      state: latest
      update_homebrew: true
